In [1]:
import os
import pandas as pd
import geopandas
import fiona
import numpy as np
import os
import csv

In [2]:
beer_data = geopandas.read_file("open-beer-database.geojson")

In [3]:
beer_data.head()

,website,city,name,cat_name,country,cat_id,brewery_id,descript,upc,srm,...,id,style_name,abv,style_id,name_breweries,address1,ibu,add_user,filepath,geometry
0,http://www.michiganbrewing.com/,Webberville,Celis Raspberry,Belgian and French Ale,United States,5,853,An authentic Belgian fruit flavored and spiced...,0.0,0.0,...,4813,Other Belgian-Style Ales,3.9,72,Michigan Brewing,1093 Highview Drive,0.0,0,None,POINT (-84.19460 42.66160)
1,http://www.bigbuck.com/gaylord.html,Gaylord,Buck Naked,North American Lager,United States,8,114,"An American-style ""light beer"". Formulated to...",0.0,0.0,...,4864,American-Style Light Lager,3.2,96,Big Buck Brewery,550 South Wisconsin Avenue,0.0,0,None,POINT (-84.68260 45.02230)
2,None,Billings,Fat Belly Amber,North American Ale,United States,3,879,None,0.0,0.0,...,93,American-Style Amber/Red Ale,0.0,33,Montana Brewing,113 North Broadway,0.0,0,None,POINT (-108.50600 45.78220)
3,None,Papillion,Belgian Wit,None,United States,-1,901,None,0.0,0.0,...,98,None,0.0,-1,Nebraska Brewing Company,7474 Towne Center Parkway #101,0.0,0,None,POINT (-96.03070 41.13390)
4,None,Missoula,Crystal Ale,None,United States,-1,122,None,0.0,0.0,...,172,None,0.0,-1,Big Sky Brewing,5417 Trumpeter Way,0.0,0,None,POINT (-114.07300 46.92230)

In [4]:
beer_data.count()

website           2879
city              5921
name              5963
cat_name          4466
country           5948
cat_id            5950
brewery_id        5963
descript          2046
upc               5944
srm               5948
last_mod          5900
state             5624
id                5973
style_name        4466
abv               5948
style_id          5949
name_breweries    5948
address1          5191
ibu               5948
add_user          5930
filepath            25
geometry          5746
dtype: int64

In [5]:
beer_data_new = beer_data[["state", "city", "name_breweries", "name", "style_name", "cat_name", "geometry"]]
beer_data_new.head()

,state,city,name_breweries,name,style_name,cat_name,geometry
0,Michigan,Webberville,Michigan Brewing,Celis Raspberry,Other Belgian-Style Ales,Belgian and French Ale,POINT (-84.19460 42.66160)
1,Michigan,Gaylord,Big Buck Brewery,Buck Naked,American-Style Light Lager,North American Lager,POINT (-84.68260 45.02230)
2,Montana,Billings,Montana Brewing,Fat Belly Amber,American-Style Amber/Red Ale,North American Ale,POINT (-108.50600 45.78220)
3,Nebraska,Papillion,Nebraska Brewing Company,Belgian Wit,None,None,POINT (-96.03070 41.13390)
4,Montana,Missoula,Big Sky Brewing,Crystal Ale,None,None,POINT (-114.07300 46.92230)

In [6]:
updated_beer_data = beer_data_new.rename(columns={"state":"State", "city":"City", "name_breweries":"Brewery", "name":"Name", "style_name":"Style", "cat_name":"Type", "geometry":"Coordinates"})
updated_beer_data.head()

,State,City,Brewery,Name,Style,Type,Coordinates
0,Michigan,Webberville,Michigan Brewing,Celis Raspberry,Other Belgian-Style Ales,Belgian and French Ale,POINT (-84.19460 42.66160)
1,Michigan,Gaylord,Big Buck Brewery,Buck Naked,American-Style Light Lager,North American Lager,POINT (-84.68260 45.02230)
2,Montana,Billings,Montana Brewing,Fat Belly Amber,American-Style Amber/Red Ale,North American Ale,POINT (-108.50600 45.78220)
3,Nebraska,Papillion,Nebraska Brewing Company,Belgian Wit,None,None,POINT (-96.03070 41.13390)
4,Montana,Missoula,Big Sky Brewing,Crystal Ale,None,None,POINT (-114.07300 46.92230)

In [8]:
nc_beer_geojson_df = updated_beer_data.loc[updated_beer_data["State"] == "North Carolina", :]
nc_beer_geojson_df.head(10)

,State,City,Brewery,Name,Style,Type,Coordinates
64,North Carolina,Asheville,Asheville Pizza and Brewing Co.,Shiva IPA,American-Style India Pale Ale,North American Ale,POINT (-82.55360 35.62210)
153,North Carolina,Chapel Hill,Carolina Brewery,IPA,American-Style India Pale Ale,North American Ale,POINT (-79.06320 35.91030)
188,North Carolina,Farmville,Duck-Rabbit Craft Brewery,Duck-Rabbit Brown Ale,American-Style Brown Ale,North American Ale,POINT (-77.59710 35.60030)
310,North Carolina,Raleigh,Big Boss Brewing Company,Angry Angel,None,None,POINT (-78.61790 35.81040)
490,North Carolina,Asheville,Highland Brewing Company,St.Terese's Pale Ale,American-Style Pale Ale,North American Ale,POINT (-82.49910 35.57160)
626,North Carolina,Raleigh,Greenshields Brewery and Pub,Amber,American-Style Amber/Red Ale,North American Ale,POINT (-78.63860 35.77210)
929,North Carolina,Raleigh,Big Boss Brewing Company,Bad Penny,American-Style Brown Ale,North American Ale,POINT (-78.61790 35.81040)
950,North Carolina,Chapel Hill,Top of the Hill Restaurant and Brewery,Big Bertha Brown,American-Style Brown Ale,North American Ale,POINT (-79.05580 35.91320)
1006,North Carolina,Asheville,Highland Brewing Company,Cold Mountain Winter Ale,Winter Warmer,Other Style,POINT (-82.49910 35.57160)
1173,North Carolina,Asheville,Asheville Pizza and Brewing Co.,Roland's ESB,Extra Special Bitter,British Ale,POINT (-82.55360 35.62210)

In [9]:
nc_beer_geojson_df.count()

State          57
City           57
Brewery        57
Name           57
Style          53
Type           53
Coordinates    57
dtype: int64